/* Shared field coordinates and drawing controls; counts are visible halves, never pin pictures. */
window.OverrideField = (() => {
 const goals=[['N1',46.66,117.3,'Top'],['B1',93.75,117.3,'Top'],['N2',23.11,93.75,'Left'],['B2',117.3,93.75,'Right'],['MID',70.2,70.2,'MID'],['R1',23.11,46.66,'Left'],['N3',117.3,46.66,'Right'],['R2',46.66,23.11,'Down'],['N4',93.75,23.11,'Down']];
 const colors={red:'#b53c4b',blue:'#286caf',neutral:'#b18417',green:'#23856a'};
 const xy=(x,y)=>[50+x*3.2,50+(140.41-y)*3.2];
 const initial={robots:[['10102C','red',17,25],['Red-1','red',17,112],['Blue 1','blue',123,115],['Blue 2','blue',123,25]],toggles:{Left:'red',Down:'red',Top:'blue',Right:'blue'},lines:[]};
 const copy=x=>JSON.parse(JSON.stringify(x));
 function mount(host, config={}) {
  const defaults=Object.assign(copy(initial),copy(config)); let state=copy(defaults), active=null, selected=null;
  const key='override-board-v2:'+location.pathname+':'+host.dataset.board;
  if(!config.counts){try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&saved.robots?.length===4&&saved.toggles&&Array.isArray(saved.lines))state=saved;}catch{}}
  host.innerHTML=`<div class="board-tools"><label>Tool <select class="tool"><option value="move">Move robots</option><option value="red">Draw red route</option><option value="blue">Draw blue route</option><option value="green">Draw note</option></select></label><button type="button" class="undo">Undo line</button><button type="button" class="reset">Reset diagram</button><button type="button" class="download">Save drawing</button><button type="button" class="share">Copy for chat</button></div><textarea class="board-note share-data" readonly hidden aria-label="Field state to paste into chat"></textarea><svg class="field-svg" viewBox="0 0 550 550" aria-label="Interactive Override field. Red driver station is on the left; 10102C starts at the bottom." role="group"></svg><div class="toggle-menu" hidden><strong></strong> <button data-color="red">Red</button> <button data-color="neutral">Neutral / touching</button> <button data-color="blue">Blue</button> <button class="close">Close</button></div><p class="subtle">Four draggable robots. Click a toggle for its color menu. Arrow keys move a focused robot. Drawings stay in this browser; save a drawing to share it in chat. Routes are sketches, not collision-checked paths.</p>`;
  const svg=host.querySelector('svg'),tool=host.querySelector('.tool'),menu=host.querySelector('.toggle-menu');
  function el(tag,attrs,parent=svg){const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);parent.append(n);return n;}
  function label(x,y,t,attrs={},parent=svg){const n=el('text',{x,y,'text-anchor':'middle','font-size':13,fill:'#263440',...attrs},parent);n.textContent=t;return n;}
  function path(points,attrs){return el('polyline',{points:points.map(p=>xy(...p).join(',')).join(' '),fill:'none',...attrs});}
  function save(){if(!config.counts)try{localStorage.setItem(key,JSON.stringify(state));}catch{}}
  function render(){svg.replaceChildren();const defs=el('defs',{});for(const[c,color]of Object.entries(colors)){const m=el('marker',{id:host.dataset.board+'-'+c,viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:5,markerHeight:5,orient:'auto'},defs);el('path',{d:'M0 0L10 5L0 10Z',fill:color},m);}
   el('rect',{x:50,y:50,width:449.31,height:449.31,rx:4,fill:'#eef1ef',stroke:'#8b979a'});
   for(let i=1;i<6;i++){path([[i*140.41/6,0],[i*140.41/6,140.41]],{stroke:'#d7dddd'});path([[0,i*140.41/6],[140.41,i*140.41/6]],{stroke:'#d7dddd'});}
   path([[46.66,70.2],[70.2,93.75],[93.75,70.2],[70.2,46.66],[46.66,70.2]],{stroke:'#bac4c6','stroke-width':2});
   label(275,20,'TOP / NORTH',{'font-size':11});label(275,540,'BOTTOM / SOUTH',{'font-size':11});
   for(const [x,y,c]of[[0,128.97,'red'],[0,11.44,'red'],[140.41,128.97,'blue'],[140.41,11.44,'blue']]){const[a,b]=xy(x,y);el('rect',{x:a-7,y:b-7,width:14,height:14,fill:colors[c]});}
   for(const[id,x,y]of goals){const[a,b]=xy(x,y);el('circle',{cx:a,cy:b,r:18,fill:id.startsWith('R')?'#f3d7da':id.startsWith('B')?'#d7e7f6':'#f5e9c4',stroke:'#8b979a'});label(a,b+4,id);if(config.counts){const n=config.counts[id]||[0,0,0];el('rect',{x:a-43,y:b+22,width:86,height:18,rx:4,fill:'#fff'});label(a,b+35,`R${n[0]} B${n[1]} Y${n[2]}`,{'font-size':11});}}
   state.lines.forEach(s=>path(s.points,{stroke:colors[s.color]||colors.green,'stroke-width':3,'stroke-linecap':'round','stroke-linejoin':'round','marker-end':`url(#${host.dataset.board}-${s.color})`}));
   for(const[id,x,y]of[['Top',70.2,140.41],['Right',140.41,70.2],['Down',70.2,0],['Left',0,70.2]]){const[a,b]=xy(x,y),c=state.toggles[id];const g=el('g',{'data-toggle':id,role:'button',tabindex:0,'aria-label':id+' toggle: '+c});el('rect',{x:a-29,y:b-15,width:58,height:30,rx:12,fill:colors[c],stroke:'#fff','stroke-width':2},g);label(a,b+4,id,{fill:'#fff'},g);g.onclick=()=>openMenu(id);g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openMenu(id);}};}
   state.robots.forEach((r,i)=>{const[a,b]=xy(r[2],r[3]),g=el('g',{'data-robot':i,role:'button',tabindex:0,'aria-label':r[0]+' robot; drag or use arrow keys'});el('rect',{x:a-27,y:b-14,width:54,height:28,rx:5,fill:'#fff',stroke:colors[r[1]],'stroke-width':2},g);label(a,b+4,r[0],{'font-size':11},g);g.onkeydown=e=>{const d={ArrowLeft:[-2,0],ArrowRight:[2,0],ArrowUp:[0,2],ArrowDown:[0,-2]}[e.key];if(d){e.preventDefault();r[2]=Math.max(6,Math.min(134,r[2]+d[0]));r[3]=Math.max(6,Math.min(134,r[3]+d[1]));render();svg.querySelector(`[data-robot="${i}"]`).focus();save();}};});
  }
  function openMenu(id){selected=id;menu.hidden=false;menu.querySelector('strong').textContent=id+' toggle';menu.querySelector('[data-color]').focus();}
  menu.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{state.toggles[selected]=b.dataset.color;config.onToggle?.(selected,b.dataset.color);render();save();menu.hidden=true;});menu.querySelector('.close').onclick=()=>menu.hidden=true;
  function point(e){const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse());return[Math.max(6,Math.min(134,(p.x-50)/3.2)),Math.max(6,Math.min(134,140.41-(p.y-50)/3.2))];}
  svg.onpointerdown=e=>{if(e.target.closest('[data-toggle]'))return;const r=e.target.closest('[data-robot]');if(tool.value==='move'){if(!r)return;active={robot:+r.dataset.robot};}else{state.lines.push({color:tool.value,points:[point(e)]});active={line:state.lines.length-1};}svg.setPointerCapture(e.pointerId);e.preventDefault();};
  svg.onpointermove=e=>{if(!active)return;const p=point(e);if(active.robot!==undefined){state.robots[active.robot][2]=p[0];state.robots[active.robot][3]=p[1];}else state.lines[active.line].points.push(p);render();};
  svg.onpointerup=svg.onpointercancel=()=>{active=null;save();};host.querySelector('.undo').onclick=()=>{state.lines.pop();render();save();};host.querySelector('.reset').onclick=()=>{state=copy(defaults);config.onReset?.();render();save();};
  host.querySelector('.download').onclick=()=>{const clone=svg.cloneNode(true);clone.setAttribute('xmlns','http://www.w3.org/2000/svg');clone.setAttribute('width','880');clone.setAttribute('height','880');clone.style.fontFamily='system-ui,sans-serif';const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml'}));const a=document.createElement('a');a.href=url;a.download=host.dataset.board+'.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  host.querySelector('.share').onclick=async()=>{const text='Discuss this Override field state. Coordinates are inches from southwest; north is up. '+JSON.stringify({robots:state.robots,toggles:state.toggles,routes:state.lines,visibleHalves:config.counts||null,finishAssumptions:config.context?.()||null});const out=host.querySelector('.share-data');out.hidden=false;out.value=text;out.focus();out.select();try{await navigator.clipboard.writeText(text);host.querySelector('.share').textContent='Copied — paste in chat';}catch{host.querySelector('.share').textContent='Select and copy the text above';}};
  render();return{update(counts,toggles){config.counts=counts;state.toggles={...toggles};render();}};
 }
 return{goals,mount};
})();
document.querySelectorAll('[data-board]:not([data-calculator])').forEach(el=>OverrideField.mount(el,JSON.parse(el.dataset.config||'{}')));
